deployment:
  tasks:
    - COMPOSER_MEMORY_LIMIT=-1 /opt/cpanel/ea-php83/root/usr/bin/php /opt/cpanel/composer/bin/composer install --working-dir=/home/msaautom/repositories/msa_proyecto --no-dev --no-interaction --prefer-dist --no-progress
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan optimize:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan filament:upgrade
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan filament:assets
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan migrate --force
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan config:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan route:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/msaautom/repositories/msa_proyecto/artisan view:cache
