---
deployment:
  tasks:
    - export DEPLOYPATH=/home/msaautom/public_html/
    - /bin/cp -r public/css $DEPLOYPATH
    - /bin/cp -r public/js $DEPLOYPATH
    - /bin/cp -r public/img $DEPLOYPATH
    - /bin/cp -r public/build $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/index.php $DEPLOYPATH
    - /bin/cp public/fix_admin.php $DEPLOYPATH
